channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=22.0.2
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
